name: Hive - Auto Sync

on:
  push:
    branches:
      - master
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Swarm Sync Endpoint
        run: |
          curl -G "https://stakgraph.swarm38.sphinx.chat/sync" \
            --header "Authorization: Bearer ${{ secrets.SWARM_API_KEY }}" \
            --data-urlencode "repo_url=https://github.com/stakwork/sphinx-tribes-frontend" \
            --data-urlencode "pat=${{ secrets.PAT }}"
